
docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker build --build-arg BUILD_NUMBER=$CI_JOB_ID  --build-arg GIT_BRANCH=$CI_COMMIT_BRANCH -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - docker system prune -f
  only:
    - main
    - test
    - postgres
