include:
  - template: Jobs/Code-Quality.gitlab-ci.yml

variables:
  PROJECT: 'ProjectPathName'

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" 
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH      

docker-build-api:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker build --build-arg BUILD_NUMBER=$CI_JOB_ID  --build-arg GIT_BRANCH=$CI_COMMIT_BRANCH -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"

nuget-push:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script:
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlabnuget --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - cd src/${PROJECT}.Core/
    - dotnet pack -c Release /p:version=8.2.$CI_JOB_ID
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlabnuget
    - cd ../${PROJECT}.DataAccess
    - dotnet pack -c Release /p:version=8.2.$CI_JOB_ID
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlabnuget
