include:
  - template: Jobs/Code-Quality.gitlab-ci.yml

variables:
  IS_API: true
  IS_WEB: true
  PROJECT: 'Amazon'

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
  rules:
    - if: $CODE_QUALITY_DISABLED
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run code quality job in merge request pipelines
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH      # Run code quality job in pipelines on the default branch (but not in other branch pipelines)

docker-build-api:
  rules:
    - if: $IS_API
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker build --build-arg BUILD_NUMBER=$CI_JOB_ID -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"


nuget-push:
  rules:
    - if: $IS_API
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == 'test'
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: build
  script:
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlabnuget --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - cd src/${PROJECT}.Core/
    - dotnet pack -c Release /p:version=8.2.$CI_JOB_ID
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlabnuget
    - cd ../${PROJECT}.DataAccess
    - dotnet pack -c Release /p:version=8.2.$CI_JOB_ID
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlabnuget

docker-build-web:
  rules:
    - if: $IS_WEB
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == 'test'
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker build --build-arg BUILD_NUMBER=$CI_JOB_ID --build-arg GIT_BRANCH=$CI_COMMIT_BRANCH -t "$DOCKER_IMAGE_NAME" -f src/Dockerfile .
    - docker push "$DOCKER_IMAGE_NAME"
