
nuget-push:
  image: mcr.microsoft.com/dotnet/sdk:9.0
  stage: nuget
  script:
  - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json"
    --name gitlabnuget --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
  - cd src/${PROJECT}.Core/
  - dotnet pack -c Release /p:version=9.0.$CI_JOB_ID-$CI_COMMIT_BRANCH
  - dotnet nuget push "bin/Release/*.nupkg" --source gitlabnuget
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "test"'
      changes:
        - src/${PROJECT}.Core/**/*
      when: on_success
