sonarqube:
  image: devops-docker.forceget.com.tr/forceget/n-tier-architecture:base-9.0
  stage: sonar
  allow_failure: true
  script:
    - dotnet sonarscanner begin /k:"${SONAR_PROJECT}" /d:sonar.host.url="https://devops-sonarqube.forceget.com.tr"  /d:sonar.token="${SONAR_TOKEN}"
    - dotnet build
    - dotnet sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
  only:
    - test
